// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_AITS.Database;

namespace Test_AITS.Migrations
{
    [DbContext(typeof(AITSDBContext))]
    [Migration("20201027035338_AssociationCommission_Table_added")]
    partial class AssociationCommission_Table_added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test_AITS.Models.AssociationCommission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CommissionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoesTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("AssociationCommissions");
                });

            modelBuilder.Entity("Test_AITS.Models.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FromAmount")
                        .HasColumnType("int");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<int>("ToAmount")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Commissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromAmount = 1000,
                            Percentage = 6f,
                            ToAmount = 10000,
                            Type = "SIDC"
                        },
                        new
                        {
                            Id = 2,
                            FromAmount = 10000,
                            Percentage = 7.5f,
                            ToAmount = 30000,
                            Type = "SIDC"
                        },
                        new
                        {
                            Id = 3,
                            FromAmount = 30000,
                            Percentage = 9f,
                            ToAmount = 60000,
                            Type = "SIDC"
                        },
                        new
                        {
                            Id = 4,
                            FromAmount = 60000,
                            Percentage = 11f,
                            ToAmount = 999999,
                            Type = "SIDC"
                        },
                        new
                        {
                            Id = 5,
                            FromAmount = 5000,
                            Percentage = 5f,
                            ToAmount = 50000,
                            Type = "AMC"
                        },
                        new
                        {
                            Id = 6,
                            FromAmount = 50000,
                            Percentage = 7f,
                            ToAmount = 999999,
                            Type = "AMC"
                        },
                        new
                        {
                            Id = 7,
                            FromAmount = 5000,
                            Percentage = 5f,
                            ToAmount = 999999,
                            Type = "BMC"
                        });
                });

            modelBuilder.Entity("Test_AITS.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Walton"
                        });
                });

            modelBuilder.Entity("Test_AITS.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DealerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsAMC")
                        .HasColumnType("int");

                    b.Property<int>("IsBMC")
                        .HasColumnType("int");

                    b.Property<int>("IsSIDC")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThanaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DealerTypeId");

                    b.HasIndex("ThanaId");

                    b.ToTable("Dealers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DealerTypeId = 1,
                            IsAMC = 0,
                            IsBMC = 0,
                            IsSIDC = 1,
                            Name = "Company",
                            ThanaId = 1
                        });
                });

            modelBuilder.Entity("Test_AITS.Models.DealerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssociateOf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DealerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GBCommission")
                        .HasColumnType("int");

                    b.Property<int>("InboundCommission")
                        .HasColumnType("int");

                    b.Property<int>("OrdinalCommission")
                        .HasColumnType("int");

                    b.Property<int>("OutboundCommission")
                        .HasColumnType("int");

                    b.Property<int>("SalesCommission")
                        .HasColumnType("int");

                    b.Property<int>("SellAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("DealerInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssociateOf = "Company",
                            DealerCode = "E-0001",
                            DealerId = 1,
                            Designation = "Company",
                            GBCommission = 0,
                            InboundCommission = 0,
                            OrdinalCommission = 0,
                            OutboundCommission = 0,
                            SalesCommission = 0,
                            SellAmount = 0
                        });
                });

            modelBuilder.Entity("Test_AITS.Models.DealerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DealerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SIDC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AMC"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BMC"
                        });
                });

            modelBuilder.Entity("Test_AITS.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DealerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GBCommission")
                        .HasColumnType("int");

                    b.Property<int>("InboundCommission")
                        .HasColumnType("int");

                    b.Property<int>("OrdinalCommission")
                        .HasColumnType("int");

                    b.Property<int>("OutboundCommission")
                        .HasColumnType("int");

                    b.Property<int>("SalesCommission")
                        .HasColumnType("int");

                    b.Property<int>("SellAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Test_AITS.Models.SalesCommission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SalesCommissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "B",
                            Percentage = 12.5f
                        },
                        new
                        {
                            Id = 2,
                            Designation = "C",
                            Percentage = 15f
                        },
                        new
                        {
                            Id = 3,
                            Designation = "D",
                            Percentage = 17.5f
                        },
                        new
                        {
                            Id = 4,
                            Designation = "E",
                            Percentage = 20f
                        },
                        new
                        {
                            Id = 5,
                            Designation = "F",
                            Percentage = 21f
                        },
                        new
                        {
                            Id = 6,
                            Designation = "G",
                            Percentage = 22f
                        },
                        new
                        {
                            Id = 7,
                            Designation = "H",
                            Percentage = 23f
                        },
                        new
                        {
                            Id = 8,
                            Designation = "I",
                            Percentage = 24f
                        },
                        new
                        {
                            Id = 9,
                            Designation = "J",
                            Percentage = 25f
                        },
                        new
                        {
                            Id = 10,
                            Designation = "K",
                            Percentage = 26f
                        });
                });

            modelBuilder.Entity("Test_AITS.Models.Thana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Thanas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Thana-A"
                        });
                });

            modelBuilder.Entity("Test_AITS.Models.AssociationCommission", b =>
                {
                    b.HasOne("Test_AITS.Models.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Test_AITS.Models.Dealer", b =>
                {
                    b.HasOne("Test_AITS.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test_AITS.Models.DealerType", "DealerType")
                        .WithMany()
                        .HasForeignKey("DealerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test_AITS.Models.Thana", "Thana")
                        .WithMany()
                        .HasForeignKey("ThanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Test_AITS.Models.DealerInfo", b =>
                {
                    b.HasOne("Test_AITS.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
